FROM ros:humble-ros-base

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-numpy \
    python3-matplotlib \
    ros-humble-rosbag2 \
    && rm -rf /var/lib/apt/lists/*

COPY map_vis.py /app/map_vis.py

ENTRYPOINT ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && exec python3 /app/map_vis.py \"$@\"", "--"]
