FROM ros:humble-ros-base

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-numpy \
    python3-matplotlib \
    ros-humble-rosbag2 \
    && rm -rf /var/lib/apt/lists/*

COPY slam_map_bag_20260226_211739 /app/bags/slam_map_bag_20260226_211739
COPY map_vis.py /app/map_vis.py

CMD ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && python3 /app/map_vis.py"]
